version: "3.8"
services:

  elasticsearch01:
    image: docker.io/library/elasticsearch:8.4.3
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      #- ${ELASTICSEARCH_DATA:-/data}/elasticsearch01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=elasticsearch01
      - node.master=true
      - node.name=node-1
      - node.data=true
      - discovery.seed_hosts=10.0.0.5
      - cluster.initial_master_nodes=10.0.0.4,10.0.0.5
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-2g} -Xmx${ES_HEAP_SIZE:-2g}"
    networks:
      - esnet
    deploy:
      placement:
        constraints: [ node.hostname == node-1 ]
    ulimits:
      memlock:
        soft: -1
        hard: -1

  elasticsearch02:
    image: docker.io/library/elasticsearch:8.4.3
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      #- ${ELASTICSEARCH_DATA:-/data}/elasticsearch02:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch02
      - node.master=true
      - node.name=node-2
      - node.data=true
      - discovery.seed_hosts=10.0.0.4
      - cluster.initial_master_nodes=10.0.0.4,10.0.0.5
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-2g} -Xmx${ES_HEAP_SIZE:-2g}"
    networks:
      - esnet
    deploy:
      placement:
        constraints: [ node.hostname == node-2 ]
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.io/library/kibana:8.4.3
    volumes:
      - type: bind
        source: ./kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - 5601:5601
    deploy:
      placement:
        constraints: [ node.hostname == node-1 ]
    networks:
      - esnet
    depends_on:
      - elasticsearch01
      - elasticsearch02

networks:
  esnet:
    driver: overlay
    attachable: true
    name: esnet